name: 'STK CLI Action'

description: 'Github Action to install STK CLI'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Install STK CLI
      run: |
        if [[ "$(uname)" = "Linux" ]]; then
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          mv /home/runner/.stk/bin/* /usr/local/bin
        elif [[ "$(uname)" = "Darwin" ]]; then
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          mv /Users/runner/.stk/bin/* /usr/local/bin
        else
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          vcpkg install curl[tool]
          cd $GITHUB_WORKSPACE
          curl https://stk.stackspot.com/installer/windows/stk.exe --output stk.exe
          ./stk.exe upgrade
          mv stk.exe /bin 
        fi  
      shell: bash

    - name: Login to StackSpot Account
      run: stk login --client-id=${{ inputs.client_id }} --client-key=${{ inputs.client_key }} --realm=${{ inputs.realm }}
      shell: bash

branding:
    icon: 'terminal'
    color: 'gray-dark'