name: Action test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-ubuntu.yml'
      - 'action.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run STK CLI installation
        uses: GuillaumeFalourd/stk-cli-action-poc@main

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Login to StackSpot Account
        continue-on-error: true
        run: stk login --client-id=0716cdea-9638-4919-9842-21dd6c73729a --client-key=2O8n3XPCuQujVFqDYvLINKYhbkQOs58v --realm=zup

      - run: stk --version
      
      - run: stk list stack

