name: Action test Windows

on:
  push:
    paths:
      - '.github/workflows/action-test-windows.yml'
      - 'action.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Run STK CLI installation
        uses: GuillaumeFalourd/stk-cli-action-poc@main
        with:
          client_id: ${{ secrets.CLIENT_ID}}
          client_key: ${{ secrets.CLIENT_KEY}}
          realm: ${{ secrets.REALM}}

      - run: stk --version
        shell: bash
      
      - run: stk list stack
        shell: bash