name: Action test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-ubuntu.yml'
      - 'action.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run STK CLI installation
        uses: GuillaumeFalourd/stk-cli-action-poc@main

      - name: Login to StackSpot Account
        continue-on-error: true
        run: stk login --client-id=$CLIENT_ID --client-key=$CLIENT_KEY --realm=$REALM 
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY}}
          REALM: ${{ secrets.REALM}}

      - name: Check logs
        if: always()
        run: cat $HOME/.stk/logs/logs/log

      - run: stk --version
      
      - run: stk list stack

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1