name: Action test Windows

on:
  push:
    paths:
      - '.github/workflows/action-test-windows.yml'
      - 'action.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Run STK CLI installation
        uses: GuillaumeFalourd/stk-cli-action-poc@main

      - name: Login to StackSpot Account
        run: stk login --client-id=$CLIENT_ID --client-key=$CLIENT_KEY --realm=$REALM 
        shell: bash        
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY}}
          REALM: ${{ secrets.REALM}}

      - run: stk --version
        shell: bash
      
      - run: stk list stack
        shell: bash