name: Action test Windows

on:
  push:
    paths:
      - 'action.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Run STK CLI installation
        uses: GuillaumeFalourd/stk-cli-action-poc@main
      
      - run: |
          pwd
          ls -lha
          cd ..
          pwd
          ls -lha
          cd ..
          pwd
          ls -lha
        shell: bash
      
      - run: stk list
        continue-on-error: true # until activation code not asked